import { ThemeProvider } from "@/components/theme-provider";
import "./globals.css";
import { Inter } from "next/font/google";
import { Nav } from "@/components/Navigation/Nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gym Track",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <main className="w-screen h-screen">
            <div className="m-2">
              {" "}
              <Nav />
              {children}
            </div>
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
